Add friends likes
xdpxrt/java-filmorate pull request #2
Opened 2023-12-08 15:02 UTC by xdpxrt

2023-12-08 16:43 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев в работе, жду новую версию

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
Все в 1 строчку влезает, к чему эти переносы

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@RequestMapping("/films")
Зачем убрали? У вас вроде все методы имеют такой префикс

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Смотрите, не совсем разобрались со слоями приложения, контроллеры должны принимать только сервис, а сервис, хранилище, пока может показаться не особо понятным для чего так делать, но потом станет яснее

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Аналогично

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Лишняя пустая строка

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
Можно инициализировать коллекцию сращу, чтобы потом не проверять на нул

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
Аналогично

2023-12-08 16:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private int countId = 1;
Можно статик по идее

2023-12-08 17:41 UTC, xdpxrt commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Мысли такие были, но что-то засомневался

2023-12-09 09:02 UTC, Frilock approved these changes
Принято, хорошо

2023-12-22 07:46 UTC, merged